version: '3.7'  
services:
  mariadb:
    container_name: mariadb 
    image: mariadb:13
    build: ./requirements/mariadb  
    volumes:
      - mariadb:/var/lib/mysql  
    networks:
      - inception  
    restart: always  
    env_file:
      - .env 

  nginx:
    container_name: nginx
    image: nginx:13
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
    env_file:
        - .env
  wordpress:
    container_name: wordpress
    image: wordpress:13
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
  redis:
    container_name: redis
    image: redis:13
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
     - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      -  wordpress:/var/www/wordpress
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 15s
      timeout: 8s
      retries: 4
    networks:
      - inception
  adminer:
    container_name: adminer
    image: adminer:13
    build: ./requirements/bonus/adminer
    restart: always
    depends_on:
      - mariadb
    ports:
    - "600:600"
    networks:
      - inception
  ftp:
    build: requirements/bonus/ftp
    image: ftp:13
    container_name: ftp
    ports:
      - "21:21"
      - "20:20"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress:/home/$UFTP/ftp/files
    networks:
      - inception
    restart: always
    env_file:
      - .env
  cadvisor:
    container_name: cadvisor
    image: cadvisor:13
    build: ./requirements/bonus/cadvisor  
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  webstatic:
    container_name: webstatic
    image: webstatic:13
    build: ./requirements/bonus/webstatics
    networks:
      - inception
    ports:
      - "3000:3000"

# MY CONFIG 
networks:
  inception:
    driver: bridge  

volumes:
  mariadb:  
    name: mariadb
    driver_opts:
      type: "none"
      o: bind
      device: $VOLUMES_PATH/mariadb
  wordpress:
    name: wordpress
    driver_opts:
      type: "none"
      o: bind
      device: $VOLUMES_PATH/wordpress